// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIFXKw04XvQGgq8r3pKeKqd5AQG9wm9qs',
    appId: '1:672494187825:web:01180a8161c32eb8ae2c10',
    messagingSenderId: '672494187825',
    projectId: 'placement-portal-app-3809b',
    authDomain: 'placement-portal-app-3809b.firebaseapp.com',
    storageBucket: 'placement-portal-app-3809b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdScJbo6MdOD2xmkz58V8YiTC0MIPEg0',
    appId: '1:672494187825:android:af25b13d7d7f2cf7ae2c10',
    messagingSenderId: '672494187825',
    projectId: 'placement-portal-app-3809b',
    storageBucket: 'placement-portal-app-3809b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALe3gO6oQdKGbsW6Z000yNys5NUUCxY0s',
    appId: '1:672494187825:ios:b2fc7a7079546d61ae2c10',
    messagingSenderId: '672494187825',
    projectId: 'placement-portal-app-3809b',
    storageBucket: 'placement-portal-app-3809b.firebasestorage.app',
    iosBundleId: 'com.example.placementPortalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALe3gO6oQdKGbsW6Z000yNys5NUUCxY0s',
    appId: '1:672494187825:ios:b2fc7a7079546d61ae2c10',
    messagingSenderId: '672494187825',
    projectId: 'placement-portal-app-3809b',
    storageBucket: 'placement-portal-app-3809b.firebasestorage.app',
    iosBundleId: 'com.example.placementPortalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIFXKw04XvQGgq8r3pKeKqd5AQG9wm9qs',
    appId: '1:672494187825:web:274681fbd21113d1ae2c10',
    messagingSenderId: '672494187825',
    projectId: 'placement-portal-app-3809b',
    authDomain: 'placement-portal-app-3809b.firebaseapp.com',
    storageBucket: 'placement-portal-app-3809b.firebasestorage.app',
  );
}
